spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fengyexjtu/config.git
          basedir: ${user.dir}/temp

          clone-on-start: true
  rabbitmq:
    addresses: 192.168.1.103
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
