#\u5F53\u524D\u5E94\u7528\u7AEF\u53E3
server:
  port: 8082
#\u5E94\u7528\u540D\u79F0
spring:
  application:
    name: user
  datasource:
    name: SpringCloudSell
    type: com.alibaba.druid.pool.DruidDataSource
    #druid\u76F8\u5173\u914D\u7F6E
    druid:
      #\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #\u57FA\u672C\u5C5E\u6027
      url: jdbc:mysql://localhost:3306/SpringCloudSell?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: edu_tutor
      password: I1lIMZqR@z.u
      #\u914D\u7F6E\u521D\u59CB\u5316\u5927\u5C0F/\u6700\u5C0F/\u6700\u5927
      initial-size: 1
      min-idle: 1
      max-active: 20
      #\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      max-wait: 60000
      #\u95F4\u9694\u591A\u4E45\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5
      time-between-eviction-runs-millis: 60000
      #\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #\u6253\u5F00PSCache\uFF0C\u5E76\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F\u3002oracle\u8BBE\u4E3Atrue\uFF0Cmysql\u8BBE\u4E3Afalse\u3002\u5206\u5E93\u5206\u8868\u8F83\u591A\u63A8\u8350\u8BBE\u7F6E\u4E3Afalse
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  #Eureka Server\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.taeyeon

#logging
logging:
  level:
    com.taeyeon.user.dao: debug
